- id: doi:10.1371/journal.pcbi.1007128
  type: paper
  description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  date: 2020-12-4
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  buttons:
    - type: manubot
      link: https://greenelab.github.io/meta-review/
    - type: source
      text: Manuscript Source
      link: https://github.com/greenelab/meta-review
    - type: website
      link: http://manubot.org/
  tags:
    - open science
    - collaboration
  repo: greenelab/meta-review

- id: doi:10.1016/j.csbj.2020.05.017
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg

- id: doi:10.7554/eLife.32822
  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp


- id: arxiv:1608.06993
  type: paper
  publisher: CVPR 2017 (Best Paper Award)
  image: images/1608.06993.jpg
  description: "<img src=\"https://img.shields.io/github/stars/liuzhuang13/DenseNet\" style=\"margin:5px ;vertical-align: middle\">"
  buttons:
    - type: paper
      link: https://arxiv.org/abs/1608.06993
    - type: source
      text: Code
      link: https://github.com/liuzhuang13/DenseNet
